G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G:\git\node\api\temp.js:87
                fs.existsSync(Desktop + "\\dist"))
                                                 ^

SyntaxError: Unexpected token )
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (G:\git\node\router\index.js:49:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
(node:1132) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (G:\git\node\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (G:\git\node\node_modules\express\lib\response.js:260:14)
    at GetFile.then.catch (G:\git\node\api\temp.js:51:21)
(node:1132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:14736) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (G:\git\node\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (G:\git\node\node_modules\express\lib\response.js:260:14)
    at GetFile.then.catch (G:\git\node\api\temp.js:50:21)
(node:14736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1720) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (G:\git\node\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (G:\git\node\node_modules\express\lib\response.js:260:14)
    at GetFile.then.catch (G:\git\node\api\temp.js:49:21)
(node:1720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
G:\git\node\node_modules\express\lib\response.js:1123
    : JSON.stringify(value);
           ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (G:\git\node\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (G:\git\node\node_modules\express\lib\response.js:260:14)
    at G:\git\node\api\temp.js:92:33
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
G:\git\node\node_modules\express\lib\response.js:1123
    : JSON.stringify(value);
           ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at stringify (G:\git\node\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (G:\git\node\node_modules\express\lib\response.js:260:14)
    at G:\git\node\api\temp.js:92:33
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.
G:\git\node\api\upcode.js:15
                throw err
                ^

Error: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.

    at ChildProcess.<anonymous> (G:\git\node\node_modules\easy-spawn\index.js:88:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.
G:\git\node\api\upcode.js:15
                throw err
                ^

Error: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.

    at ChildProcess.<anonymous> (G:\git\node\node_modules\easy-spawn\index.js:88:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.
G:\git\node\api\upcode.js:15
                throw err
                ^

Error: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.

    at ChildProcess.<anonymous> (G:\git\node\node_modules\easy-spawn\index.js:88:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.
G:\git\node\api\upcode.js:15
                throw err
                ^

Error: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.

    at ChildProcess.<anonymous> (G:\git\node\node_modules\easy-spawn\index.js:88:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.
G:\git\node\api\upcode.js:15
                throw err
                ^

Error: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.

    at ChildProcess.<anonymous> (G:\git\node\node_modules\easy-spawn\index.js:88:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.
G:\git\node\api\upcode.js:15
                throw err
                ^

Error: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.

    at ChildProcess.<anonymous> (G:\git\node\node_modules\easy-spawn\index.js:88:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.
G:\git\node\api\upcode.js:15
                throw err
                ^

Error: svn: E155004: Run 'svn cleanup' to remove locks (type 'svn help cleanup' for details)
svn: E155004: Working copy 'G:\aoneQt' locked.
svn: E155004: 'G:\aoneQt' is already locked.

    at ChildProcess.<anonymous> (G:\git\node\node_modules\easy-spawn\index.js:88:25)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
G:\git\node\app.js:10
    if (err) throw err;
    ^

ReferenceError: err is not defined
    at Object.<anonymous> (G:\git\node\app.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
G:\git\node\app.js:10
    if (err) throw err;
    ^

ReferenceError: err is not defined
    at Object.<anonymous> (G:\git\node\app.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
G:\git\node\app.js:10
    if (err) throw err;
    ^

ReferenceError: err is not defined
    at Object.<anonymous> (G:\git\node\app.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
G:\git\node\app.js:10
    if (err) throw err;
    ^

ReferenceError: err is not defined
    at Object.<anonymous> (G:\git\node\app.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
G:\git\node\app.js:10
    if (err) throw err;
    ^

ReferenceError: err is not defined
    at Object.<anonymous> (G:\git\node\app.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
G:\git\node\app.js:10
    if (err) throw err;
    ^

ReferenceError: err is not defined
    at Object.<anonymous> (G:\git\node\app.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:5792) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:5792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5792) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:5792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6544) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8096) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:8096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8096) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:8096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8096) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:8096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:8096) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:8096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:8096) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:8096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:8096) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:8096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:8096) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:8096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:6644) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6644) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6644) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6644) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:6644) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:6644) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:6036) UnhandledPromiseRejectionWarning: ReferenceError: data is not defined
    at global.GET_FILE_CONTENT.then.resolve (G:\git\node\api\temp.js:143:48)
(node:6036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
